spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tsinjo_std23035_prod
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration,classpath:db/migration/prod

vola:
  api-key: ${API_KEY}
